In [1]:
import pandas as pd
import numpy as np
import scipy.io as io
import os
import csv


In [3]:
import torch

# 加载权重文件
weights_path = r'E:\new_radar\cnn_last.pth'
model = torch.load(weights_path)

# 查看模型结构
print(model)

CNN(
  (conv1): Sequential(
    (0): Conv1d(1, 64, kernel_size=(8,), stride=(1,), bias=False)
    (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv2): Sequential(
    (0): Conv1d(64, 128, kernel_size=(16,), stride=(1,), bias=False)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv3): Sequential(
    (0): Conv1d(128, 256, kernel_size=(32,), stride=(1,), bias=False)
    (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv4): Sequential(
    (0): Conv1d(256, 512, kernel_size=(64,), stride=(1,), bias=False)
    (1): Ba

In [7]:
signal = np.load("labels.npy")
print(signal.shape)
print(signal.dtype)
# for index, row in enumerate(signal):
#     print(f"行索引：{index}, 行数据：{row}")
    

(36000,)
float64


In [3]:
path = r"X:\pystudy\radar\SIGNAL\data_signal"

In [4]:
list_name = []
list_file_name = []
for file in os.listdir(path):
    file_path = os.path.join(path,file)
    if os.path.splitext(file_path)[1] == '.mat':
        list_name.append(file_path)
        list_file_name.append(file)
list_file_name

['A_10_1000dB.mat',
 'A_10_1001dB.mat',
 'A_10_1002dB.mat',
 'A_10_1003dB.mat',
 'A_10_1004dB.mat',
 'A_10_1005dB.mat',
 'A_10_1006dB.mat',
 'A_10_1007dB.mat',
 'A_10_1008dB.mat',
 'A_10_1009dB.mat',
 'A_10_100dB.mat',
 'A_10_1010dB.mat',
 'A_10_1011dB.mat',
 'A_10_1012dB.mat',
 'A_10_1013dB.mat',
 'A_10_1014dB.mat',
 'A_10_1015dB.mat',
 'A_10_1016dB.mat',
 'A_10_1017dB.mat',
 'A_10_1018dB.mat',
 'A_10_1019dB.mat',
 'A_10_101dB.mat',
 'A_10_1020dB.mat',
 'A_10_1021dB.mat',
 'A_10_1022dB.mat',
 'A_10_1023dB.mat',
 'A_10_1024dB.mat',
 'A_10_1025dB.mat',
 'A_10_1026dB.mat',
 'A_10_1027dB.mat',
 'A_10_1028dB.mat',
 'A_10_1029dB.mat',
 'A_10_102dB.mat',
 'A_10_1030dB.mat',
 'A_10_1031dB.mat',
 'A_10_1032dB.mat',
 'A_10_1033dB.mat',
 'A_10_1034dB.mat',
 'A_10_1035dB.mat',
 'A_10_1036dB.mat',
 'A_10_1037dB.mat',
 'A_10_1038dB.mat',
 'A_10_1039dB.mat',
 'A_10_103dB.mat',
 'A_10_1040dB.mat',
 'A_10_1041dB.mat',
 'A_10_1042dB.mat',
 'A_10_1043dB.mat',
 'A_10_1044dB.mat',
 'A_10_1045dB.mat',
 'A_

In [5]:
tempdata = np.zeros((36000,1,2000))
tempdata[0][0][:]


array([0., 0., 0., ..., 0., 0., 0.])

In [6]:
test = io.loadmat(list_name[1])
test['Signal']

array([[-0.29131177+2.82127638j, -5.23097093-6.35813967j,
        -7.62332585+4.34886178j, ..., -8.34005032-0.75917232j,
        -1.0488726 -1.45746123j,  0.52877814+3.11657361j]])

In [7]:
t = np.transpose(np.array(test['Signal']))
t

array([[-0.29131177+2.82127638j],
       [-5.23097093-6.35813967j],
       [-7.62332585+4.34886178j],
       ...,
       [-8.34005032-0.75917232j],
       [-1.0488726 -1.45746123j],
       [ 0.52877814+3.11657361j]])

In [8]:
for i in range(2000):
    tempdata[0][0][i] = t[i].real
tempdata[0][0][:]

array([-0.29131177, -5.23097093, -7.62332585, ..., -8.34005032,
       -1.0488726 ,  0.52877814])

In [9]:
labels = np.zeros(36000)

label = {'A':0, 'B':1, 'C':2}

In [10]:
for i in range(len(list_name)):
    data = io.loadmat(list_name[i])
    sig = np.transpose(np.array(data['Signal']))
    for j in range(2000):
        tempdata[i][0][j] = sig[j].real
    if data['label'] == 'A':
        labels[i] = label['A']
    elif data['label'] == 'B':
        labels[i] = label['B']
    else:
        labels[i] = label['C']



In [31]:
tempdata,labels

(array([[[-1.64479073e+00, -8.41860210e+00,  5.16813985e+00, ...,
          -4.71874062e+00, -4.42601218e+00, -6.19516338e+00]],
 
        [[-2.91311771e-01, -5.23097093e+00, -7.62332585e+00, ...,
          -8.34005032e+00, -1.04887260e+00,  5.28778137e-01]],
 
        [[-1.45908927e+00,  1.42453148e-01, -2.72647492e+00, ...,
           7.07064103e+00, -1.08563678e+00,  2.06820737e+00]],
 
        ...,
 
        [[-2.07395620e+00,  9.19063454e+00,  8.00258823e+00, ...,
           3.24858439e+00,  1.23235123e+01,  3.28889491e+00]],
 
        [[ 8.09134279e+00,  9.06438957e-01, -2.55423177e+00, ...,
          -4.49667372e+00,  9.77432266e-03, -3.23553977e+00]],
 
        [[-1.20835292e+01,  5.18300730e+00,  3.11724255e+00, ...,
           4.01809502e+00,  1.43424056e+01, -1.04161037e+01]]]),
 array([1., 1., 1., ..., 3., 3., 3.]))

In [11]:
np.save("signal.npy",tempdata)


In [12]:
np.save("labels.npy",labels)